steps:
  # Install Node.js dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
    
  # Build the React app
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.simple', '-t', '$_IMAGE_NAME', '.']
    
  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE_NAME']

substitutions:
  _IMAGE_NAME: 'gcr.io/$PROJECT_ID/cnidaria-admin-curves'

images:
  - '$_IMAGE_NAME'
